name: model_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.7
  - pip
  - pip:
      - mlflow
      - pandas
      - numpy
      - scikit-learn
      - dagshub
      - PySastrawi